/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateVolumeBackendDto } from './create-volume-backend-dto';

export interface CreateVolume {
    'name': string;
    /**
     * Storage backend. Omit to create a Daytona-managed S3 volume.
     */
    'backend'?: CreateVolumeBackendDto;
}

