/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DtoJuiceFSVolumeSourceDTO } from './dto-juice-fsvolume-source-dto';

export interface DtoVolumeBackendDTO {
    'juicefs'?: DtoJuiceFSVolumeSourceDTO;
    'type': DtoVolumeBackendDTOTypeEnum;
}
export const DtoVolumeBackendDTOTypeEnum = {
    MANAGED_S3: 'managed_s3',
    JUICEFS: 'juicefs',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type DtoVolumeBackendDTOTypeEnum = typeof DtoVolumeBackendDTOTypeEnum[keyof typeof DtoVolumeBackendDTOTypeEnum];
