/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DtoVolumeBackendDTO } from './dto-volume-backend-dto';

export interface DtoVolumeDTO {
    'backend'?: DtoVolumeBackendDTO;
    'mountPath'?: string;
    'subpath'?: string;
    'volumeId'?: string;
}

