/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DtoVolumeDTO } from './dto-volume-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { DtoVolumeMountCredentialDTO } from './dto-volume-mount-credential-dto';

export interface StartSandboxDTO {
    'metadata'?: { [key: string]: string; };
    'volumeMountCredentials'?: { [key: string]: DtoVolumeMountCredentialDTO; };
    'volumes'?: Array<DtoVolumeDTO>;
}
