/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.daytona.api.client.model.JuiceFSVolumeCredentialDto;
import io.daytona.api.client.model.VolumeBackendType;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.daytona.api.client.JSON;

/**
 * CreateVolumeBackendDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CreateVolumeBackendDto {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private VolumeBackendType type;

  public static final String SERIALIZED_NAME_META_URL = "metaUrl";
  @SerializedName(SERIALIZED_NAME_META_URL)
  @javax.annotation.Nullable
  private String metaUrl;

  public static final String SERIALIZED_NAME_BUCKET = "bucket";
  @SerializedName(SERIALIZED_NAME_BUCKET)
  @javax.annotation.Nullable
  private String bucket;

  public static final String SERIALIZED_NAME_CACHE_SIZE_MI_B = "cacheSizeMiB";
  @SerializedName(SERIALIZED_NAME_CACHE_SIZE_MI_B)
  @javax.annotation.Nullable
  private BigDecimal cacheSizeMiB = new BigDecimal("10240");

  public static final String SERIALIZED_NAME_CAPACITY_GI_B = "capacityGiB";
  @SerializedName(SERIALIZED_NAME_CAPACITY_GI_B)
  @javax.annotation.Nullable
  private BigDecimal capacityGiB = new BigDecimal("50");

  public static final String SERIALIZED_NAME_CREDENTIAL = "credential";
  @SerializedName(SERIALIZED_NAME_CREDENTIAL)
  @javax.annotation.Nullable
  private JuiceFSVolumeCredentialDto credential;

  public CreateVolumeBackendDto() {
  }

  public CreateVolumeBackendDto type(@javax.annotation.Nonnull VolumeBackendType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public VolumeBackendType getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull VolumeBackendType type) {
    this.type = type;
  }


  public CreateVolumeBackendDto metaUrl(@javax.annotation.Nullable String metaUrl) {
    this.metaUrl = metaUrl;
    return this;
  }

  /**
   * Get metaUrl
   * @return metaUrl
   */
  @javax.annotation.Nullable
  public String getMetaUrl() {
    return metaUrl;
  }

  public void setMetaUrl(@javax.annotation.Nullable String metaUrl) {
    this.metaUrl = metaUrl;
  }


  public CreateVolumeBackendDto bucket(@javax.annotation.Nullable String bucket) {
    this.bucket = bucket;
    return this;
  }

  /**
   * Optional object storage URL passed to JuiceFS mount as --bucket.
   * @return bucket
   */
  @javax.annotation.Nullable
  public String getBucket() {
    return bucket;
  }

  public void setBucket(@javax.annotation.Nullable String bucket) {
    this.bucket = bucket;
  }


  public CreateVolumeBackendDto cacheSizeMiB(@javax.annotation.Nullable BigDecimal cacheSizeMiB) {
    this.cacheSizeMiB = cacheSizeMiB;
    return this;
  }

  /**
   * Get cacheSizeMiB
   * minimum: 0
   * @return cacheSizeMiB
   */
  @javax.annotation.Nullable
  public BigDecimal getCacheSizeMiB() {
    return cacheSizeMiB;
  }

  public void setCacheSizeMiB(@javax.annotation.Nullable BigDecimal cacheSizeMiB) {
    this.cacheSizeMiB = cacheSizeMiB;
  }


  public CreateVolumeBackendDto capacityGiB(@javax.annotation.Nullable BigDecimal capacityGiB) {
    this.capacityGiB = capacityGiB;
    return this;
  }

  /**
   * Capacity reported by JuiceFS to mounted sandboxes, in GiB.
   * minimum: 1
   * @return capacityGiB
   */
  @javax.annotation.Nullable
  public BigDecimal getCapacityGiB() {
    return capacityGiB;
  }

  public void setCapacityGiB(@javax.annotation.Nullable BigDecimal capacityGiB) {
    this.capacityGiB = capacityGiB;
  }


  public CreateVolumeBackendDto credential(@javax.annotation.Nullable JuiceFSVolumeCredentialDto credential) {
    this.credential = credential;
    return this;
  }

  /**
   * Get credential
   * @return credential
   */
  @javax.annotation.Nullable
  public JuiceFSVolumeCredentialDto getCredential() {
    return credential;
  }

  public void setCredential(@javax.annotation.Nullable JuiceFSVolumeCredentialDto credential) {
    this.credential = credential;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreateVolumeBackendDto instance itself
   */
  public CreateVolumeBackendDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVolumeBackendDto createVolumeBackendDto = (CreateVolumeBackendDto) o;
    return Objects.equals(this.type, createVolumeBackendDto.type) &&
        Objects.equals(this.metaUrl, createVolumeBackendDto.metaUrl) &&
        Objects.equals(this.bucket, createVolumeBackendDto.bucket) &&
        Objects.equals(this.cacheSizeMiB, createVolumeBackendDto.cacheSizeMiB) &&
        Objects.equals(this.capacityGiB, createVolumeBackendDto.capacityGiB) &&
        Objects.equals(this.credential, createVolumeBackendDto.credential)&&
        Objects.equals(this.additionalProperties, createVolumeBackendDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, metaUrl, bucket, cacheSizeMiB, capacityGiB, credential, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVolumeBackendDto {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    metaUrl: ").append(toIndentedString(metaUrl)).append("\n");
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    cacheSizeMiB: ").append(toIndentedString(cacheSizeMiB)).append("\n");
    sb.append("    capacityGiB: ").append(toIndentedString(capacityGiB)).append("\n");
    sb.append("    credential: ").append(toIndentedString(credential)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "metaUrl", "bucket", "cacheSizeMiB", "capacityGiB", "credential"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateVolumeBackendDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateVolumeBackendDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateVolumeBackendDto is not found in the empty JSON string", CreateVolumeBackendDto.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateVolumeBackendDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `type`
      VolumeBackendType.validateJsonElement(jsonObj.get("type"));
      if ((jsonObj.get("metaUrl") != null && !jsonObj.get("metaUrl").isJsonNull()) && !jsonObj.get("metaUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `metaUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("metaUrl").toString()));
      }
      if ((jsonObj.get("bucket") != null && !jsonObj.get("bucket").isJsonNull()) && !jsonObj.get("bucket").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bucket` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bucket").toString()));
      }
      // validate the optional field `credential`
      if (jsonObj.get("credential") != null && !jsonObj.get("credential").isJsonNull()) {
        JuiceFSVolumeCredentialDto.validateJsonElement(jsonObj.get("credential"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateVolumeBackendDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateVolumeBackendDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateVolumeBackendDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateVolumeBackendDto.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateVolumeBackendDto>() {
           @Override
           public void write(JsonWriter out, CreateVolumeBackendDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateVolumeBackendDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CreateVolumeBackendDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateVolumeBackendDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateVolumeBackendDto
   * @throws IOException if the JSON string is invalid with respect to CreateVolumeBackendDto
   */
  public static CreateVolumeBackendDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateVolumeBackendDto.class);
  }

  /**
   * Convert an instance of CreateVolumeBackendDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
