=begin
#Daytona

#Daytona AI platform API Docs

The version of the OpenAPI document: 1.0
Contact: support@daytona.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module DaytonaApiClient
  class CreateVolumeBackendDto < ApiModelBase
    attr_accessor :type

    attr_accessor :meta_url

    # Optional object storage URL passed to JuiceFS mount as --bucket.
    attr_accessor :bucket

    attr_accessor :cache_size_mi_b

    # Capacity reported by JuiceFS to mounted sandboxes, in GiB.
    attr_accessor :capacity_gi_b

    attr_accessor :credential

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'meta_url' => :'metaUrl',
        :'bucket' => :'bucket',
        :'cache_size_mi_b' => :'cacheSizeMiB',
        :'capacity_gi_b' => :'capacityGiB',
        :'credential' => :'credential'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'VolumeBackendType',
        :'meta_url' => :'String',
        :'bucket' => :'String',
        :'cache_size_mi_b' => :'Float',
        :'capacity_gi_b' => :'Float',
        :'credential' => :'JuiceFSVolumeCredentialDto'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DaytonaApiClient::CreateVolumeBackendDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DaytonaApiClient::CreateVolumeBackendDto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'meta_url')
        self.meta_url = attributes[:'meta_url']
      end

      if attributes.key?(:'bucket')
        self.bucket = attributes[:'bucket']
      end

      if attributes.key?(:'cache_size_mi_b')
        self.cache_size_mi_b = attributes[:'cache_size_mi_b']
      else
        self.cache_size_mi_b = 10240
      end

      if attributes.key?(:'capacity_gi_b')
        self.capacity_gi_b = attributes[:'capacity_gi_b']
      else
        self.capacity_gi_b = 50
      end

      if attributes.key?(:'credential')
        self.credential = attributes[:'credential']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if !@cache_size_mi_b.nil? && @cache_size_mi_b < 0
        invalid_properties.push('invalid value for "cache_size_mi_b", must be greater than or equal to 0.')
      end

      if !@capacity_gi_b.nil? && @capacity_gi_b < 1
        invalid_properties.push('invalid value for "capacity_gi_b", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      return false if !@cache_size_mi_b.nil? && @cache_size_mi_b < 0
      return false if !@capacity_gi_b.nil? && @capacity_gi_b < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] cache_size_mi_b Value to be assigned
    def cache_size_mi_b=(cache_size_mi_b)
      if cache_size_mi_b.nil?
        fail ArgumentError, 'cache_size_mi_b cannot be nil'
      end

      if cache_size_mi_b < 0
        fail ArgumentError, 'invalid value for "cache_size_mi_b", must be greater than or equal to 0.'
      end

      @cache_size_mi_b = cache_size_mi_b
    end

    # Custom attribute writer method with validation
    # @param [Object] capacity_gi_b Value to be assigned
    def capacity_gi_b=(capacity_gi_b)
      if capacity_gi_b.nil?
        fail ArgumentError, 'capacity_gi_b cannot be nil'
      end

      if capacity_gi_b < 1
        fail ArgumentError, 'invalid value for "capacity_gi_b", must be greater than or equal to 1.'
      end

      @capacity_gi_b = capacity_gi_b
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          meta_url == o.meta_url &&
          bucket == o.bucket &&
          cache_size_mi_b == o.cache_size_mi_b &&
          capacity_gi_b == o.capacity_gi_b &&
          credential == o.credential
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, meta_url, bucket, cache_size_mi_b, capacity_gi_b, credential].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
