/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// VolumeBackendType the model 'VolumeBackendType'
type VolumeBackendType string

// List of VolumeBackendType
const (
	VOLUMEBACKENDTYPE_MANAGED_S3               VolumeBackendType = "managed_s3"
	VOLUMEBACKENDTYPE_JUICEFS                  VolumeBackendType = "juicefs"
	VOLUMEBACKENDTYPE_UNKNOWN_DEFAULT_OPEN_API VolumeBackendType = "11184809"
)

// All allowed values of VolumeBackendType enum
var AllowedVolumeBackendTypeEnumValues = []VolumeBackendType{
	"managed_s3",
	"juicefs",
	"11184809",
}

func (v *VolumeBackendType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VolumeBackendType(value)
	for _, existing := range AllowedVolumeBackendTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = VOLUMEBACKENDTYPE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewVolumeBackendTypeFromValue returns a pointer to a valid VolumeBackendType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVolumeBackendTypeFromValue(v string) (*VolumeBackendType, error) {
	ev := VolumeBackendType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := VOLUMEBACKENDTYPE_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VolumeBackendType) IsValid() bool {
	for _, existing := range AllowedVolumeBackendTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VolumeBackendType value
func (v VolumeBackendType) Ptr() *VolumeBackendType {
	return &v
}

type NullableVolumeBackendType struct {
	value *VolumeBackendType
	isSet bool
}

func (v NullableVolumeBackendType) Get() *VolumeBackendType {
	return v.value
}

func (v *NullableVolumeBackendType) Set(val *VolumeBackendType) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeBackendType) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeBackendType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeBackendType(val *VolumeBackendType) *NullableVolumeBackendType {
	return &NullableVolumeBackendType{value: val, isSet: true}
}

func (v NullableVolumeBackendType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeBackendType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
