/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the JuiceFSVolumeCredentialDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JuiceFSVolumeCredentialDto{}

// JuiceFSVolumeCredentialDto struct for JuiceFSVolumeCredentialDto
type JuiceFSVolumeCredentialDto struct {
	// Password for the JuiceFS metadata engine.
	MetaPassword         *string `json:"metaPassword,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JuiceFSVolumeCredentialDto JuiceFSVolumeCredentialDto

// NewJuiceFSVolumeCredentialDto instantiates a new JuiceFSVolumeCredentialDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJuiceFSVolumeCredentialDto() *JuiceFSVolumeCredentialDto {
	this := JuiceFSVolumeCredentialDto{}
	return &this
}

// NewJuiceFSVolumeCredentialDtoWithDefaults instantiates a new JuiceFSVolumeCredentialDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJuiceFSVolumeCredentialDtoWithDefaults() *JuiceFSVolumeCredentialDto {
	this := JuiceFSVolumeCredentialDto{}
	return &this
}

// GetMetaPassword returns the MetaPassword field value if set, zero value otherwise.
func (o *JuiceFSVolumeCredentialDto) GetMetaPassword() string {
	if o == nil || IsNil(o.MetaPassword) {
		var ret string
		return ret
	}
	return *o.MetaPassword
}

// GetMetaPasswordOk returns a tuple with the MetaPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JuiceFSVolumeCredentialDto) GetMetaPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.MetaPassword) {
		return nil, false
	}
	return o.MetaPassword, true
}

// HasMetaPassword returns a boolean if a field has been set.
func (o *JuiceFSVolumeCredentialDto) HasMetaPassword() bool {
	if o != nil && !IsNil(o.MetaPassword) {
		return true
	}

	return false
}

// SetMetaPassword gets a reference to the given string and assigns it to the MetaPassword field.
func (o *JuiceFSVolumeCredentialDto) SetMetaPassword(v string) {
	o.MetaPassword = &v
}

func (o JuiceFSVolumeCredentialDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JuiceFSVolumeCredentialDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetaPassword) {
		toSerialize["metaPassword"] = o.MetaPassword
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JuiceFSVolumeCredentialDto) UnmarshalJSON(data []byte) (err error) {
	varJuiceFSVolumeCredentialDto := _JuiceFSVolumeCredentialDto{}

	err = json.Unmarshal(data, &varJuiceFSVolumeCredentialDto)

	if err != nil {
		return err
	}

	*o = JuiceFSVolumeCredentialDto(varJuiceFSVolumeCredentialDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "metaPassword")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJuiceFSVolumeCredentialDto struct {
	value *JuiceFSVolumeCredentialDto
	isSet bool
}

func (v NullableJuiceFSVolumeCredentialDto) Get() *JuiceFSVolumeCredentialDto {
	return v.value
}

func (v *NullableJuiceFSVolumeCredentialDto) Set(val *JuiceFSVolumeCredentialDto) {
	v.value = val
	v.isSet = true
}

func (v NullableJuiceFSVolumeCredentialDto) IsSet() bool {
	return v.isSet
}

func (v *NullableJuiceFSVolumeCredentialDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJuiceFSVolumeCredentialDto(val *JuiceFSVolumeCredentialDto) *NullableJuiceFSVolumeCredentialDto {
	return &NullableJuiceFSVolumeCredentialDto{value: val, isSet: true}
}

func (v NullableJuiceFSVolumeCredentialDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJuiceFSVolumeCredentialDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
