/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// VolumeLifecycle the model 'VolumeLifecycle'
type VolumeLifecycle string

// List of VolumeLifecycle
const (
	VOLUMELIFECYCLE_MANAGED                  VolumeLifecycle = "managed"
	VOLUMELIFECYCLE_EXTERNAL                 VolumeLifecycle = "external"
	VOLUMELIFECYCLE_UNKNOWN_DEFAULT_OPEN_API VolumeLifecycle = "11184809"
)

// All allowed values of VolumeLifecycle enum
var AllowedVolumeLifecycleEnumValues = []VolumeLifecycle{
	"managed",
	"external",
	"11184809",
}

func (v *VolumeLifecycle) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VolumeLifecycle(value)
	for _, existing := range AllowedVolumeLifecycleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = VOLUMELIFECYCLE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewVolumeLifecycleFromValue returns a pointer to a valid VolumeLifecycle
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVolumeLifecycleFromValue(v string) (*VolumeLifecycle, error) {
	ev := VolumeLifecycle(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := VOLUMELIFECYCLE_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VolumeLifecycle) IsValid() bool {
	for _, existing := range AllowedVolumeLifecycleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VolumeLifecycle value
func (v VolumeLifecycle) Ptr() *VolumeLifecycle {
	return &v
}

type NullableVolumeLifecycle struct {
	value *VolumeLifecycle
	isSet bool
}

func (v NullableVolumeLifecycle) Get() *VolumeLifecycle {
	return v.value
}

func (v *NullableVolumeLifecycle) Set(val *VolumeLifecycle) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeLifecycle) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeLifecycle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeLifecycle(val *VolumeLifecycle) *NullableVolumeLifecycle {
	return &NullableVolumeLifecycle{value: val, isSet: true}
}

func (v NullableVolumeLifecycle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeLifecycle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
