/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateVolumeBackendDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVolumeBackendDto{}

// CreateVolumeBackendDto struct for CreateVolumeBackendDto
type CreateVolumeBackendDto struct {
	Type    VolumeBackendType `json:"type"`
	MetaUrl *string           `json:"metaUrl,omitempty"`
	// Optional object storage URL passed to JuiceFS mount as --bucket.
	Bucket       *string  `json:"bucket,omitempty"`
	CacheSizeMiB *float32 `json:"cacheSizeMiB,omitempty"`
	// Capacity reported by JuiceFS to mounted sandboxes, in GiB.
	CapacityGiB          *float32                    `json:"capacityGiB,omitempty"`
	Credential           *JuiceFSVolumeCredentialDto `json:"credential,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateVolumeBackendDto CreateVolumeBackendDto

// NewCreateVolumeBackendDto instantiates a new CreateVolumeBackendDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVolumeBackendDto(type_ VolumeBackendType) *CreateVolumeBackendDto {
	this := CreateVolumeBackendDto{}
	this.Type = type_
	var cacheSizeMiB float32 = 10240
	this.CacheSizeMiB = &cacheSizeMiB
	var capacityGiB float32 = 50
	this.CapacityGiB = &capacityGiB
	return &this
}

// NewCreateVolumeBackendDtoWithDefaults instantiates a new CreateVolumeBackendDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVolumeBackendDtoWithDefaults() *CreateVolumeBackendDto {
	this := CreateVolumeBackendDto{}
	var cacheSizeMiB float32 = 10240
	this.CacheSizeMiB = &cacheSizeMiB
	var capacityGiB float32 = 50
	this.CapacityGiB = &capacityGiB
	return &this
}

// GetType returns the Type field value
func (o *CreateVolumeBackendDto) GetType() VolumeBackendType {
	if o == nil {
		var ret VolumeBackendType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateVolumeBackendDto) GetTypeOk() (*VolumeBackendType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateVolumeBackendDto) SetType(v VolumeBackendType) {
	o.Type = v
}

// GetMetaUrl returns the MetaUrl field value if set, zero value otherwise.
func (o *CreateVolumeBackendDto) GetMetaUrl() string {
	if o == nil || IsNil(o.MetaUrl) {
		var ret string
		return ret
	}
	return *o.MetaUrl
}

// GetMetaUrlOk returns a tuple with the MetaUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeBackendDto) GetMetaUrlOk() (*string, bool) {
	if o == nil || IsNil(o.MetaUrl) {
		return nil, false
	}
	return o.MetaUrl, true
}

// HasMetaUrl returns a boolean if a field has been set.
func (o *CreateVolumeBackendDto) HasMetaUrl() bool {
	if o != nil && !IsNil(o.MetaUrl) {
		return true
	}

	return false
}

// SetMetaUrl gets a reference to the given string and assigns it to the MetaUrl field.
func (o *CreateVolumeBackendDto) SetMetaUrl(v string) {
	o.MetaUrl = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *CreateVolumeBackendDto) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeBackendDto) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *CreateVolumeBackendDto) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *CreateVolumeBackendDto) SetBucket(v string) {
	o.Bucket = &v
}

// GetCacheSizeMiB returns the CacheSizeMiB field value if set, zero value otherwise.
func (o *CreateVolumeBackendDto) GetCacheSizeMiB() float32 {
	if o == nil || IsNil(o.CacheSizeMiB) {
		var ret float32
		return ret
	}
	return *o.CacheSizeMiB
}

// GetCacheSizeMiBOk returns a tuple with the CacheSizeMiB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeBackendDto) GetCacheSizeMiBOk() (*float32, bool) {
	if o == nil || IsNil(o.CacheSizeMiB) {
		return nil, false
	}
	return o.CacheSizeMiB, true
}

// HasCacheSizeMiB returns a boolean if a field has been set.
func (o *CreateVolumeBackendDto) HasCacheSizeMiB() bool {
	if o != nil && !IsNil(o.CacheSizeMiB) {
		return true
	}

	return false
}

// SetCacheSizeMiB gets a reference to the given float32 and assigns it to the CacheSizeMiB field.
func (o *CreateVolumeBackendDto) SetCacheSizeMiB(v float32) {
	o.CacheSizeMiB = &v
}

// GetCapacityGiB returns the CapacityGiB field value if set, zero value otherwise.
func (o *CreateVolumeBackendDto) GetCapacityGiB() float32 {
	if o == nil || IsNil(o.CapacityGiB) {
		var ret float32
		return ret
	}
	return *o.CapacityGiB
}

// GetCapacityGiBOk returns a tuple with the CapacityGiB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeBackendDto) GetCapacityGiBOk() (*float32, bool) {
	if o == nil || IsNil(o.CapacityGiB) {
		return nil, false
	}
	return o.CapacityGiB, true
}

// HasCapacityGiB returns a boolean if a field has been set.
func (o *CreateVolumeBackendDto) HasCapacityGiB() bool {
	if o != nil && !IsNil(o.CapacityGiB) {
		return true
	}

	return false
}

// SetCapacityGiB gets a reference to the given float32 and assigns it to the CapacityGiB field.
func (o *CreateVolumeBackendDto) SetCapacityGiB(v float32) {
	o.CapacityGiB = &v
}

// GetCredential returns the Credential field value if set, zero value otherwise.
func (o *CreateVolumeBackendDto) GetCredential() JuiceFSVolumeCredentialDto {
	if o == nil || IsNil(o.Credential) {
		var ret JuiceFSVolumeCredentialDto
		return ret
	}
	return *o.Credential
}

// GetCredentialOk returns a tuple with the Credential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeBackendDto) GetCredentialOk() (*JuiceFSVolumeCredentialDto, bool) {
	if o == nil || IsNil(o.Credential) {
		return nil, false
	}
	return o.Credential, true
}

// HasCredential returns a boolean if a field has been set.
func (o *CreateVolumeBackendDto) HasCredential() bool {
	if o != nil && !IsNil(o.Credential) {
		return true
	}

	return false
}

// SetCredential gets a reference to the given JuiceFSVolumeCredentialDto and assigns it to the Credential field.
func (o *CreateVolumeBackendDto) SetCredential(v JuiceFSVolumeCredentialDto) {
	o.Credential = &v
}

func (o CreateVolumeBackendDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVolumeBackendDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.MetaUrl) {
		toSerialize["metaUrl"] = o.MetaUrl
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.CacheSizeMiB) {
		toSerialize["cacheSizeMiB"] = o.CacheSizeMiB
	}
	if !IsNil(o.CapacityGiB) {
		toSerialize["capacityGiB"] = o.CapacityGiB
	}
	if !IsNil(o.Credential) {
		toSerialize["credential"] = o.Credential
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateVolumeBackendDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateVolumeBackendDto := _CreateVolumeBackendDto{}

	err = json.Unmarshal(data, &varCreateVolumeBackendDto)

	if err != nil {
		return err
	}

	*o = CreateVolumeBackendDto(varCreateVolumeBackendDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "metaUrl")
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "cacheSizeMiB")
		delete(additionalProperties, "capacityGiB")
		delete(additionalProperties, "credential")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateVolumeBackendDto struct {
	value *CreateVolumeBackendDto
	isSet bool
}

func (v NullableCreateVolumeBackendDto) Get() *CreateVolumeBackendDto {
	return v.value
}

func (v *NullableCreateVolumeBackendDto) Set(val *CreateVolumeBackendDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVolumeBackendDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVolumeBackendDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVolumeBackendDto(val *CreateVolumeBackendDto) *NullableCreateVolumeBackendDto {
	return &NullableCreateVolumeBackendDto{value: val, isSet: true}
}

func (v NullableCreateVolumeBackendDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVolumeBackendDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
