/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the VolumeBackendDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumeBackendDto{}

// VolumeBackendDto struct for VolumeBackendDto
type VolumeBackendDto struct {
	Type                 VolumeBackendType `json:"type"`
	MetaUrl              *string           `json:"metaUrl,omitempty"`
	Bucket               *string           `json:"bucket,omitempty"`
	CacheSizeMiB         *float32          `json:"cacheSizeMiB,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VolumeBackendDto VolumeBackendDto

// NewVolumeBackendDto instantiates a new VolumeBackendDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeBackendDto(type_ VolumeBackendType) *VolumeBackendDto {
	this := VolumeBackendDto{}
	this.Type = type_
	return &this
}

// NewVolumeBackendDtoWithDefaults instantiates a new VolumeBackendDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeBackendDtoWithDefaults() *VolumeBackendDto {
	this := VolumeBackendDto{}
	return &this
}

// GetType returns the Type field value
func (o *VolumeBackendDto) GetType() VolumeBackendType {
	if o == nil {
		var ret VolumeBackendType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *VolumeBackendDto) GetTypeOk() (*VolumeBackendType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *VolumeBackendDto) SetType(v VolumeBackendType) {
	o.Type = v
}

// GetMetaUrl returns the MetaUrl field value if set, zero value otherwise.
func (o *VolumeBackendDto) GetMetaUrl() string {
	if o == nil || IsNil(o.MetaUrl) {
		var ret string
		return ret
	}
	return *o.MetaUrl
}

// GetMetaUrlOk returns a tuple with the MetaUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeBackendDto) GetMetaUrlOk() (*string, bool) {
	if o == nil || IsNil(o.MetaUrl) {
		return nil, false
	}
	return o.MetaUrl, true
}

// HasMetaUrl returns a boolean if a field has been set.
func (o *VolumeBackendDto) HasMetaUrl() bool {
	if o != nil && !IsNil(o.MetaUrl) {
		return true
	}

	return false
}

// SetMetaUrl gets a reference to the given string and assigns it to the MetaUrl field.
func (o *VolumeBackendDto) SetMetaUrl(v string) {
	o.MetaUrl = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *VolumeBackendDto) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeBackendDto) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *VolumeBackendDto) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *VolumeBackendDto) SetBucket(v string) {
	o.Bucket = &v
}

// GetCacheSizeMiB returns the CacheSizeMiB field value if set, zero value otherwise.
func (o *VolumeBackendDto) GetCacheSizeMiB() float32 {
	if o == nil || IsNil(o.CacheSizeMiB) {
		var ret float32
		return ret
	}
	return *o.CacheSizeMiB
}

// GetCacheSizeMiBOk returns a tuple with the CacheSizeMiB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeBackendDto) GetCacheSizeMiBOk() (*float32, bool) {
	if o == nil || IsNil(o.CacheSizeMiB) {
		return nil, false
	}
	return o.CacheSizeMiB, true
}

// HasCacheSizeMiB returns a boolean if a field has been set.
func (o *VolumeBackendDto) HasCacheSizeMiB() bool {
	if o != nil && !IsNil(o.CacheSizeMiB) {
		return true
	}

	return false
}

// SetCacheSizeMiB gets a reference to the given float32 and assigns it to the CacheSizeMiB field.
func (o *VolumeBackendDto) SetCacheSizeMiB(v float32) {
	o.CacheSizeMiB = &v
}

func (o VolumeBackendDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumeBackendDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.MetaUrl) {
		toSerialize["metaUrl"] = o.MetaUrl
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.CacheSizeMiB) {
		toSerialize["cacheSizeMiB"] = o.CacheSizeMiB
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VolumeBackendDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVolumeBackendDto := _VolumeBackendDto{}

	err = json.Unmarshal(data, &varVolumeBackendDto)

	if err != nil {
		return err
	}

	*o = VolumeBackendDto(varVolumeBackendDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "metaUrl")
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "cacheSizeMiB")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVolumeBackendDto struct {
	value *VolumeBackendDto
	isSet bool
}

func (v NullableVolumeBackendDto) Get() *VolumeBackendDto {
	return v.value
}

func (v *NullableVolumeBackendDto) Set(val *VolumeBackendDto) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeBackendDto) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeBackendDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeBackendDto(val *VolumeBackendDto) *NullableVolumeBackendDto {
	return &NullableVolumeBackendDto{value: val, isSet: true}
}

func (v NullableVolumeBackendDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeBackendDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
