/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.daytona.api.client.model.VolumeBackendType;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VolumeBackendDto
 */
public class VolumeBackendDtoTest {
    private final VolumeBackendDto model = new VolumeBackendDto();

    /**
     * Model tests for VolumeBackendDto
     */
    @Test
    public void testVolumeBackendDto() {
        // TODO: test VolumeBackendDto
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'metaUrl'
     */
    @Test
    public void metaUrlTest() {
        // TODO: test metaUrl
    }

    /**
     * Test the property 'cacheSizeMiB'
     */
    @Test
    public void cacheSizeMiBTest() {
        // TODO: test cacheSizeMiB
    }

}
